version: '3.3'

services:
  # Servidor PHP
  php-fpm:
    build:
      args:
        user: ${SO_USER}
        uid: ${SO_USER_ID}
      context: ./docker/php-fpm
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: ${APP_AlIAS}_web
    extra_hosts:
      - "host.docker.internal:host-gateway"
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    ports:
      - "${APP_PORT}:80"
    networks:
      - laratest

  # redis
  redis:
    build:
        context: ./docker/redis
    restart: unless-stopped
    container_name: ${APP_AlIAS}_redis
    volumes:
      - ./docker/redis:/data
    ports:
      - "${DOCKER_REDIS_EXTERNAL_PORT}:6379"
    networks:
      - laratest

  postgres:
    build:
      context: ./docker/postgres
    restart: unless-stopped
    volumes:
      - db-postgres:/var/lib/postgresql/data
    ports:
      - "${DOCKER_EXTERNAL_DB_PORT}:5432"
    extra_hosts:
      # IMPORTANT: Replace with your Docker Host IP (will be appended to /etc/hosts)
      - "dockerhost:${DOCKER_HOST_IP}"
    environment:
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    container_name: ${APP_AlIAS}_database
    networks:
      - laratest

networks:
  laratest:
    driver: bridge

volumes:
    db-postgres:
        driver: local
